### ISSUE TITLE
make failed at: error: ‘as_variable_ref’ is not a member of ‘torch::autograd’          return torch::autograd

### ISSUE THREAD

**Issue by HCMY** [Angel-ML/PyTorch-On-Angel#112]
hey guys, I've encounted a promlem at make statge
> PyTorch-On-Angel/cpp/include/angel/pytorch/model.h:71:33: error: ‘as_variable_ref’ is not a member of ‘torch::autograd’
         return torch::autograd::as_variable_ref(p.value);
....
Cmake[2]: *** [CMakeFiles/torch_angel.dir/src/angel/pytorch/angel_torch.cc.o] Interrupt
make[2]: *** [CMakeFiles/torch_angel.dir/src/angel/pytorch/model.cc.o] Interrupt
make[1]: *** [CMakeFiles/torch_angel.dir/all] Interrupt 

>my env is:
python 3.7
jdk 1.8
maven 3.6.2
gcc 7.1.0
libtorch 1.9.0
pytorch 1.9.0
cmake 3.12.2
cuda 10.2

is anyone knows how to solve it? thanks a lot!

**Comment by ouyangwen-it** [comment]
请使用1.5.0版本的pytorch和libtorch，readme主页有版本要求说明

**Comment by HCMY** [comment]
> 请使用1.5.0版本的pytorch和libtorch，readme主页有版本要求说明
非常感谢！
