### ISSUE TITLE
模型训练报错

### ISSUE THREAD

**Issue by kettlelinna** [Angel-ML/PyTorch-On-Angel#21]
User class threw exception: java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
![image](https://user-images.githubusercontent.com/58110598/88911444-70ee2400-d290-11ea-9600-f07c5762345e.png)

**Comment by kettlelinna** [comment]
看样子是上传归档包的归档包--archives torch.zip#torch没有到达java.library.path

**Comment by GolLonger** [comment]
兄弟，你解决没，我们也遇到这个问题了。

**Comment by GolLonger** [comment]
兄弟，我解决了。

**Comment by ouyangwen-it** [comment]
> User class threw exception: java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
> java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
> ![image](https://user-images.githubusercontent.com/58110598/88911444-70ee2400-d290-11ea-9600-f07c5762345e.png)

这个是因为你打的archives包解压后的目录和你配置的不匹配，
![Uploading image.png…]()

**Comment by kettlelinna** [comment]
谢谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ouyang Wen"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 下午5:33
收件人: "Angel-ML/PyTorch-On-Angel"<PyTorch-On-Angel@noreply.github.com&gt;; 
抄送: "天打雷劈屠真龙"<1042892985@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Angel-ML/PyTorch-On-Angel] 模型训练报错 (#21)





  
User class threw exception: java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
 java.lang.UnsatisfiedLinkError: no torch_angel in java.library.path
 
  
这个是因为你打的archives包解压后的目录和你配置的不匹配，
