### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by XingweiChen** [Angel-ML/PyTorch-On-Angel#4]
I follow the instruction[Compilation & Deployment Instructions] to compile and deploy on my mac. But the following error occurred. 
![image](https://user-images.githubusercontent.com/22898959/63632282-d049ba00-c665-11e9-9e89-3a5bc5df7b5f.png)
![image](https://user-images.githubusercontent.com/22898959/63632465-fb81d880-c668-11e9-87f0-8975821d3919.png)
Seems "jni_md.h" is not found on the specified directory. How can deal with it?

**Comment by ouyangwen-it** [comment]
> I follow the instruction[Compilation & Deployment Instructions] to compile and deploy on my mac. But the following error occurred.
> ![image](https://user-images.githubusercontent.com/22898959/63632282-d049ba00-c665-11e9-9e89-3a5bc5df7b5f.png)
> ![image](https://user-images.githubusercontent.com/22898959/63632465-fb81d880-c668-11e9-87f0-8975821d3919.png)
> Seems "jni_md.h" is not found on the specified directory. How can deal with it?

set include path in CMakeList.txt.

**Comment by leleyu** [comment]
This problem is caused by "cannot find jni_md.h" and jni_md.h is existed under the directory of Headers/darwin.
So maybe you can add one "include_directories(${JAVA_INCLUDE_PATH}/darwin)" line in the CMakeLists.txt

**Comment by XingweiChen** [comment]
Thank you for your reply. However after add "include_directories(${JAVA_INCLUDE_PATH}/darwin)" line, I got following error.
![image](https://user-images.githubusercontent.com/22898959/63669301-33755100-c80c-11e9-9fc6-624e19404c0c.png)
